### ISSUE TITLE
Heroku "Application error"

### ISSUE THREAD

**Issue by AsafTzarfati** [jw84/messenger-bot-witai-tutorial#11]
The project has  a problem.
I cloned it and all I get is "Application error" from Heroku.

**Comment by neeraj87** [comment]
@asaf1989 please post heroku logs here so its easier for us to diagnose the problem. 

To see the app logs do the following:

In your terminal:

`heroku login`

After you successfully login

`heroku logs --app appname`

**Comment by contreuno** [comment]
I am having the same issue. Could you help me out ?

My log is :
2017-01-17T22:05:15.839101+00:00 app[api]: Initial release by user nicolascsayer@gmail.com
2017-01-17T22:05:15.839101+00:00 app[api]: Release v1 created by user nicolascsayer@gmail.com
2017-01-17T22:05:15.968162+00:00 app[api]: Release v2 created by user nicolascsayer@gmail.com
2017-01-17T22:05:15.968162+00:00 app[api]: Enable Logplex by user nicolascsayer@gmail.com
2017-01-17T22:06:39.090416+00:00 app[api]: Deploy 7709aef by user nicolascsayer@gmail.com
2017-01-17T22:06:39.426761+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-17T22:06:39.426771+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-17T22:06:39.090416+00:00 app[api]: Release v3 created by user nicolascsayer@gmail.com
2017-01-17T22:06:39.109242+00:00 app[api]: Scaled to web@1:Free by user nicolascsayer@gmail.com
2017-01-17T22:06:41.288897+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-17T22:06:44.628803+00:00 app[web.1]: /app/config.js:5
2017-01-17T22:06:44.628826+00:00 app[web.1]:   throw new Error('Missing WIT_TOKEN. Go to https://wit.ai/docs/quickstart to get one.')
2017-01-17T22:06:44.628827+00:00 app[web.1]:   ^
2017-01-17T22:06:44.628828+00:00 app[web.1]: 
2017-01-17T22:06:44.628828+00:00 app[web.1]: Error: Missing WIT_TOKEN. Go to https://wit.ai/docs/quickstart to get one.
2017-01-17T22:06:44.628829+00:00 app[web.1]:     at Object.<anonymous> (/app/config.js:5:9)
2017-01-17T22:06:44.628830+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-17T22:06:44.628831+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-17T22:06:44.628832+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-01-17T22:06:44.628831+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-17T22:06:44.628833+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-01-17T22:06:44.628833+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-01-17T22:06:44.628834+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-17T22:06:44.628835+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-17T22:06:44.628834+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:7:14)
2017-01-17T22:06:44.710191+00:00 heroku[web.1]: Process exited with status 1
2017-01-17T22:06:44.736594+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-17T22:06:44.737726+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-17T22:06:46.088842+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-17T22:06:48.625873+00:00 app[web.1]: /app/config.js:5
2017-01-17T22:06:48.625886+00:00 app[web.1]:   throw new Error('Missing WIT_TOKEN. Go to https://wit.ai/docs/quickstart to get one.')
2017-01-17T22:06:48.625886+00:00 app[web.1]:   ^
2017-01-17T22:06:48.625887+00:00 app[web.1]: 
2017-01-17T22:06:48.625888+00:00 app[web.1]: Error: Missing WIT_TOKEN. Go to https://wit.ai/docs/quickstart to get one.
2017-01-17T22:06:48.625889+00:00 app[web.1]:     at Object.<anonymous> (/app/config.js:5:9)
2017-01-17T22:06:48.625890+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-17T22:06:48.625891+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-17T22:06:48.625891+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-17T22:06:48.625892+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-01-17T22:06:48.625893+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-01-17T22:06:48.625893+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-01-17T22:06:48.625894+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-17T22:06:48.625895+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:7:14)
2017-01-17T22:06:48.625895+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-17T22:06:48.730859+00:00 heroku[web.1]: Process exited with status 1
2017-01-17T22:06:48.738592+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-17T22:06:55.844946+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=young-shelf-70634.herokuapp.com request_id=8e21cf7f-f735-4f5d-af13-d2c356edf19c fwd="176.160.5.106" dyno= connect= service= status=503 bytes=
2017-01-17T22:06:56.232692+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=young-shelf-70634.herokuapp.com request_id=72d0cc2b-39ad-436a-840a-5ccafbbb305c fwd="176.160.5.106" dyno= connect= service= status=503 bytes=

**Comment by colinking** [comment]
"Error: Missing WIT_TOKEN. Go to https://wit.ai/docs/quickstart to get one."

You need to set your WIT_TOKEN config variable in Heroku (Settings > Reveal Config Variables).

**Comment by SammyMwanyasi** [comment]
Am assuming you copied the clone without inspecting anything therefore you've no idea of whats  going on. As a first aid add a new file and call it **runtime** then inside it specify the programming language version that was used to code the repo. eg. python 2.7.10
