### ISSUE TITLE
Unable to run $ node index.js

### ISSUE THREAD

**Issue by ethanow** [jw84/messenger-bot-witai-tutorial#4]
I got the following error which prevented me from running the bot. 

In the terminal, I tried to run 

`$ node index.js`

but the following error was returned:

```
module.js:442
    throw err;
    ^

Error: Cannot find module 'node-wit'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/macbookair13/Desktop/BudgetBot/services/wit.js:5:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

After i deploy, my Heroku shows the same error

```
2016-07-13T17:08:23.902935+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-07-13T17:08:23.902926+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-07-13T17:08:23.902927+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-07-13T17:08:23.902928+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-07-13T17:08:23.902929+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-07-13T17:08:24.786494+00:00 heroku[web.1]: Process exited with status 1
2016-07-13T17:08:24.789328+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by jellyfangs** [comment]
That means you haven't install the node-wit node package yet.

Run

`npm install --save node-wit`

The --save flag will save the package to the package.json file so that the next time you upload to Heroku it will be replicated and installed there too.
